# Generated by Django 5.0.6 on 2024-07-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='creayed_at',
            new_name='created_at',
        ),
    ]
