# Generated by Django 5.0.6 on 2024-07-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_rename_creayed_at_tweet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
