# Generated by Django 5.0.6 on 2024-07-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_customuser_instahandle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='instaHandle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
