# Generated by Django 5.0.6 on 2024-07-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_rename_coverimage_customuser_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='instaHandle',
            new_name='instagram',
        ),
    ]
