# Generated by Django 5.0.6 on 2024-07-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_rename_instahandle_customuser_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
