# Generated by Django 5.0.6 on 2024-07-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_alter_customuser_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
