# Generated by Django 5.0.6 on 2024-07-06 14:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0012_rename_cover_image_customuser_coverimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='profile_Image/')),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='cover_Image/')),
                ('bio', models.TextField(blank=True)),
                ('tweets_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
