# Generated by Django 5.0.6 on 2024-07-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0013_tweetuserdata_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetuserdata',
            old_name='firstName',
            new_name='first_name',
        ),
    ]
