# Generated by Django 5.0.6 on 2024-07-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0015_rename_coverimage_tweetuserdata_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetuserdata',
            old_name='birthDate',
            new_name='birth_Date',
        ),
    ]
